"""Build incident reports as JSON, Markdown, and (optionally) PDF.

Reports are written under ``<data_dir>/reports/``. If ``OPSCOMMANDER_MODE=aws``
and an S3 bucket is configured, artifacts are also uploaded to S3 and the S3
URI is returned alongside the local path.
"""

from __future__ import annotations

import json
import os

from ..config import Settings, get_settings
from ..logging_config import get_logger
from ..models import Incident

log = get_logger("reporting")


class ReportBuilder:
    def __init__(self, settings: Settings | None = None):
        self.settings = settings or get_settings()
        self.dir = os.path.join(self.settings.local_store_dir, "reports")
        os.makedirs(self.dir, exist_ok=True)

    def build(self, incident: Incident) -> dict[str, str]:
        """Return a mapping of format -> URI for each artifact produced."""
        artifacts: dict[str, str] = {}

        json_path = os.path.join(self.dir, f"{incident.id}.json")
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump(incident.to_dict(), fh, indent=2, default=str)
        artifacts["json"] = json_path

        md_path = os.path.join(self.dir, f"{incident.id}.md")
        markdown = self.render_markdown(incident)
        with open(md_path, "w", encoding="utf-8") as fh:
            fh.write(markdown)
        artifacts["markdown"] = md_path

        pdf_path = self._maybe_pdf(incident, markdown)
        if pdf_path:
            artifacts["pdf"] = pdf_path

        self._maybe_upload_s3(incident, artifacts)
        return artifacts

    # ------------------------------------------------------------------ #
    def render_markdown(self, incident: Incident) -> str:
        rec_lines = [
            f"{i+1}. **{r.title}** (`{r.action}`, confidence {r.confidence:.0%})\n"
            f"   - {r.rationale}"
            + (
                "\n   - References: " + ", ".join(r.references)
                if r.references
                else ""
            )
            for i, r in enumerate(incident.recommendations)
        ] or ["_No recommendations produced._"]

        timeline_lines = [
            f"- `{t.timestamp}` **[{t.stage}]** {t.message}" for t in incident.timeline
        ]

        approval = incident.approval
        remediation = incident.remediation

        return "\n".join(
            [
                f"# Incident Report - {incident.title}",
                "",
                f"- **Incident ID:** `{incident.id}`",
                f"- **Service:** {incident.service}",
                f"- **Alarm:** {incident.alarm}",
                f"- **Severity:** {incident.severity.value}",
                f"- **Status:** {incident.status.value}",
                f"- **Created:** {incident.created_at}",
                f"- **Updated:** {incident.updated_at}",
                "",
                "## Root Cause Analysis",
                "",
                incident.root_cause or "_Undetermined._",
                "",
                "## Recommendations",
                "",
                *rec_lines,
                "",
                "## Approval Decision",
                "",
                (
                    f"- **Action:** `{approval.action}`\n"
                    f"- **Risk:** {approval.risk}\n"
                    f"- **Approved:** {approval.approved} "
                    f"({'automatic' if approval.auto else 'manual required'})\n"
                    f"- **Reason:** {approval.reason}"
                    if approval
                    else "_No approval decision recorded._"
                ),
                "",
                "## Remediation",
                "",
                (
                    f"- **Action:** `{remediation.action}`\n"
                    f"- **Executed:** {remediation.executed}\n"
                    f"- **Success:** {remediation.success}\n"
                    f"- **Detail:** {remediation.detail}"
                    if remediation
                    else "_No remediation performed._"
                ),
                "",
                "## Timeline",
                "",
                *timeline_lines,
                "",
                "---",
                "_Generated by OpsCommander multi-agent incident response._",
                "",
            ]
        )

    # ------------------------------------------------------------------ #
    def _maybe_pdf(self, incident: Incident, markdown: str) -> str | None:
        try:
            from reportlab.lib.pagesizes import LETTER  # type: ignore
            from reportlab.lib.units import inch  # type: ignore
            from reportlab.pdfgen import canvas  # type: ignore
        except ImportError:
            log.info("reportlab not installed; skipping PDF")
            return None

        path = os.path.join(self.dir, f"{incident.id}.pdf")
        try:
            c = canvas.Canvas(path, pagesize=LETTER)
            width, height = LETTER
            y = height - inch
            for raw in markdown.splitlines():
                line = raw.replace("**", "").replace("`", "").replace("#", "").strip()
                if y < inch:
                    c.showPage()
                    y = height - inch
                c.setFont("Helvetica", 10)
                c.drawString(inch, y, line[:100])
                y -= 14
            c.save()
            return path
        except Exception as exc:  # noqa: BLE001
            log.warning("PDF generation failed: %s", exc)
            return None

    def _maybe_upload_s3(self, incident: Incident, artifacts: dict[str, str]) -> None:
        if self.settings.is_mock or not self.settings.s3_bucket:
            return
        from ..aws.clients import make_client

        s3 = make_client("s3", self.settings)
        if s3 is None:
            return
        for fmt, path in list(artifacts.items()):
            key = f"reports/{incident.id}.{fmt if fmt != 'markdown' else 'md'}"
            try:
                s3.upload_file(path, self.settings.s3_bucket, key)
                if fmt == "json":
                    artifacts["s3"] = f"s3://{self.settings.s3_bucket}/{key}"
            except Exception as exc:  # noqa: BLE001
                log.warning("S3 upload failed for %s: %s", key, exc)
